### PR TITLE
fix Joi module name of Uppercase to lowercase for require

### PR DESCRIPTION
**Pull request by davidenq**

### CODE REVIEW

**Comment by jsumners** [comment]
Thank you. Don't know how it was even working with that mistake.

**Comment by davidenq** [comment]
Thank for hapi-marko module. Could you update package in npm?

**Comment by jsumners** [comment]
Yes. I'm going to update npm shortly.

**Comment by jsumners** [comment]
It's now published as 0.3.2

**Comment by davidenq** [comment]
Thank you.

**Pull request merged**
